shopNow/urls.py
from django.views.static import serve
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.urls import include, re_path



urlpatterns = [
    path('admin/', admin.site.urls),
    # path('ckeditor/', include('ckeditor.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    re_path(r'^', include(('web.urls', 'web'), namespace="web")),

    re_path('media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # re_path('static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_FILE_ROOT}),
    re_path('static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

web/urls.py
from django.urls import path
from web.views import *
app_name = "web"
urlpatterns = [

	path('', myHome.as_view(), name="home"),
	path('myShop', myShop.as_view(), name="myShop"),
	path('productDetails/<int:pk>/', productDetails.as_view(), name="productDetails"),
	path('shopCart', shopCart.as_view(), name="shopCart"),
	path('contact', contact.as_view(), name="contact"),
	path('checkOut', checkOut.as_view(), name="checkOut"),
	path('refundPolicy', refundPolicy.as_view(), name="refundPolicy"),
	path('shippingPolicy', shippingPolicy.as_view(), name="shippingPolicy"),
	path('privacyPolicy', privacyPolicy.as_view(), name="privacyPolicy"),
	path('aboutUs', aboutUs.as_view(), name="aboutUs"),
	path('newsLetter', newsLetter.as_view(), name="newsLetter")

]

templates/about_us.html
{% extends "base.html" %}
{% load static %}
{% block body %}

    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="/"><i class="fa fa-home"></i> Home</a>
                        <span>Shipping Policy</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Shop Section Begin -->
    <section class="shop spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <h1>ABOUT US</h1>
                   
                    Welcome to EFUDEXSTORE<br>
                    Starting as a small business in India, we have big dreams. Our passion for creative products, means that we provide our customers with nothing but the highest quality of products, that are guaranteed to meet their needs and keep them satisfied!
                    With a motivated team, we strive to be the creative minds that bring a smile to your face. That’s why we’re always looking for innovative new ways to get the best to you.
                </div>
            </div>
        </div>
    </section>
    <!-- Shop Section End -->

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ashion Template">
    <meta name="keywords" content="Ashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Efudex Store</title>

    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'img/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'img/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'img/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'img/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'img/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">


    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cookie&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@900&display=swap" rel="stylesheet">
    
    

    <!-- Css Styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <!-- <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css"> -->
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magiczoomplus.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/sweet-alert.css' %}" type="text/css" />
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Offcanvas Menu Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="offcanvas__close">+</div>
        
        <div class="offcanvas__logo">
            <a href="shop-cart.html">
                <h1>EFUDEX STORE</h1>
            </a>
        </div>
        <div style="position:relative" class="header__right__widget">
            <form>
                <input type="text" placeholder="Serch here" name="q" required >
                <span style="position:absolute;position: absolute; right: 19px; top: 19px;font-size: 15px;" class="icon_search search-switch"></span> 
            </form>
                    
        </div>
        <div id="mobile-menu-wrap"></div>
    </div>
    <!-- Offcanvas Menu End -->

    <!-- Header Section Begin -->
    <div class="col-12" style="color:orangered;font-weight:700!important;text-align:center;background:#004aac;font-family:'Montserrat', sans-serif;padding-bottom:5px;padding-top:5px" >FREE DELIVERY ANYWHERE IN INDIA ! <img src="{% static 'img/sale.png'%}"></div>
    <header class="header">
        
        <div class="container-fluid"> 
            <div class="row">    
                <div class="col-xl-3 col-lg-2">
                    <div class="header__logo">
                        <h1 style="font-size:30px"><span style="background-color: blue;">EFUDEX </span>STORE</h1>
                    </div>
                </div>
                <div class="col-xl-6 col-lg-7">
                    <nav class="header__menu">
                        <ul>
                            <li {% if request.resolver_match.url_name == 'home' %}class="active"{% endif %}><a href="/">Home</a></li>
                            <li {% if request.resolver_match.url_name == 'myShop' %}class="active"{% endif %}><a href="{% url 'web:myShop' %}">Shop</a></li>
                            <li {% if request.resolver_match.url_name == 'contact' %}class="active"{% endif %}><a href="{% url 'web:contact' %}">Contact</a></li>
                        </ul>
                    </nav>
                </div>
                
                <div class="col-lg-3 srch " {% if request.resolver_match.url_name != 'contact' %}style="display:block"{% endif %}>
                    <div class="header__right">
                        <div style="position:relative" class="header__right__widget">
                            <form action ="" method="GET">
                                {% csrf_token %}
                                <input type="text" placeholder="Serch here" name="q" required >
                                <button type="submit" style="position:absolute;position: absolute; right: 19px; top: 19px;font-size: 15px;border: none;background: #fff;" class="icon_search search-switch"></button> 
                            </form>
                                    
                        </div>
                    </div>
                </div>
            </div>
            <div class="canvas__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>
    <!-- Header Section End -->

{% block body %}
{% endblock %}

<!-- Footer Section Begin -->
<footer class="footer" style="background: #5555;">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-5">
                <div class="footer__widget">
                    <h6>Customer Service</h6>
                    <ul>
                        <li><a href="index.html#">Mon to Fri : 9AM to 5PM</a></li>
                        <li><a href="index.html#">@efudexstore@gmail.com</a></li>
                        
                    </ul>
                </div>
                
            </div>
            <div class="col-lg-4 col-md-3 col-sm-5">
                <div class="footer__widget">
                    <h6>Quick links</h6>
                    <ul>
                        <li><a href="/refundPolicy">Refund Policy</a></li>
                        <li><a href="/shippingPolicy">Shipping Policy</a></li>
                        <li><a href="/privacyPolicy">Privacy Policy</a></li>
                        <li><a href="/aboutUs">About Us</a></li>
                        <li><a href="/contact">Contact Us</a></li>
                    </ul>
                </div>
            </div>
            
           
            <div class="col-lg-4 col-md-8 col-sm-8">
                <div class="footer__newslatter">
                    <h6>NEWSLETTER</h6>
                    <form action="\newsLetter" class="checkout__form ajax reload redirect" method="POST">
                        {% csrf_token %}
                        <input type="email" placeholder="Email" name="email" required >
                        <input type="submit" style="position: absolute;right: 0px; top: 0px;width:150px;color:#fff" class="site-btn" value="Subscribe"></input>
                    </form>
                   
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                <div class="footer__copyright__text">
                    <p>Copyright &copy; {% now 'Y' %} All rights reserved Efudexstore</p>
                </div>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section End -->


<!-- Js Plugins -->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<!--<script src="{% static 'js/jquery-ui.min.js' %}"></script>-->
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="{% static 'js/mixitup.min.js' %}"></script>
<script src="{% static 'js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/magiczoomplus.js' %}"></script>
<script src="{% static 'js/cart.js' %}"></script>
<script type="text/javascript" src="{% static 'js/sweet-alert.min.js' %}"></script>
</body>

</html>

templates/checkout.html
{% extends "base.html" %}
{% load static %}
{% block body %}
    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="index.html"><i class="fa fa-home"></i> Home</a>
                        <span>Shopping cart</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Checkout Section Begin -->
    <section class="checkout spad">
        <div class="container">
            <form  action="/checkOut" class="checkout__form ajax reload redirect" method="POST"> 
                {% csrf_token %}    
                <div class="row">
                    <div class="col-lg-6" style="margin-bottom:3%">
                        <div class="checkout__order">
                            <div class="row">
                                <div style="position:relative">
                                    <img src="{{pdt.bannerImage}}" class="cart-img">
                                    <span class="pdt_count">{{pdtQty}}</span>
                                </div>

                                
                                <div class="col-8">
                                
                                    
                                        <div style="line-height:4em;font-weight:bold">
                                            {{pdt.name}}
                                            <span style="float:right;font-family: cursive !important;font-size: 30px;">₹ {{pdt.offer_price}}</span>
                                        </div>
                                        
                                   
                                </div>
                            </div>
                            

                            <div class="checkout__order__product">
                                
                            </div>
                            <div class="checkout__order__total">
                                <ul>
                                    <li>Subtotal <span class="total_cart" style="font-family: cursive !important;font-size: 30px;">₹{{total_price}}</span></li>
                                </ul>
                            </div>
                
                            <input id="order_place" type="submit" class="site-btn" value="Place Your oder">
                        </div>
                    </div> 
                    <div class="col-lg-6">
                        <h5>Billing detail</h5>
                        <div class="row">
                            <input type="hidden" name="pdtId" value="{{ pdt.id }}">
                            <input type="hidden" name="pdtQty" value="{{ pdtQty }}">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="checkout__form__input">
                                    <p>First Name <span style="color :red">*</span></p>
                                    <input type="text" name ="first_name" required>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="checkout__form__input">
                                    <p>Last Name <span style="color :red">*</span></p>
                                    <input type="text" name ="last_name" required>
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="checkout__form__input">
                                    <p>Country <span style="color :red">*</span></p>
                                    <input type="text" name="country" value="india" readonly>
                                </div>
                                <div class="checkout__form__input">
                                    <p>Address <span style="color :red">*</span></p>
                                    {% comment %} <input type="text" name="address"> {% endcomment %}
                                    <textarea  style="resize:none"  name="address" class="tag form-control" rows="4" cols="50" required ></textarea>
                                </div>
                                <div class="checkout__form__input">
                                    <p>Apartment <span></span></p>
                                    <input type="text" name="apartment">
                                </div>
                                <div class="checkout__form__input">
                                    <p>Town/City <span style="color :red">*</span></p>
                                    <input type="text" name="town_city" required>
                                </div>
                                <div class="checkout__form__input">
                                    <p>State <span style="color :red">*</span></p>
                                    
                                    <!--- India states -->
                                        <select id="select_state" name="state" required>
                                            <option value="ANAndaman and Nicobar Islands">Andaman and Nicobar Islands</option>
                                            <option value="Andhra Pradesh">Andhra Pradesh</option>
                                            <option value="Arunachal Pradesh">Arunachal Pradesh</option>
                                            <option value="Assam">Assam</option>
                                            <option value="Bihar">Bihar</option>
                                            <option value="Chandigarh">Chandigarh</option>
                                            <option value="Chhattisgarh">Chhattisgarh</option>
                                            <option value="Dadra and Nagar Haveli">Dadra and Nagar Haveli</option>
                                            <option value="Daman and Diu">Daman and Diu</option>
                                            <option value="Delhi">Delhi</option>
                                            <option value="Goa">Goa</option>
                                            <option value="Gujarat">Gujarat</option>
                                            <option value="Haryana">Haryana</option>
                                            <option value="Himachal Pradesh">Himachal Pradesh</option>
                                            <option value="Jammu and Kashmir">Jammu and Kashmir</option>
                                            <option value="Jharkhand">Jharkhand</option>
                                            <option value="Karnataka">Karnataka</option>
                                            <option value="Kerala">Kerala</option>
                                            <option value="Ladakh">Ladakh</option>
                                            <option value="Lakshadweep">Lakshadweep</option>
                                            <option value="Madhya Pradesh">Madhya Pradesh</option>
                                            <option value="Maharashtra">Maharashtra</option>
                                            <option value="Manipur">Manipur</option>
                                            <option value="Meghalaya">Meghalaya</option>
                                            <option value="Mizoram">Mizoram</option>
                                            <option value="Nagaland">Nagaland</option>
                                            <option value="Odisha">Odisha</option>
                                            <option value="Puducherry">Puducherry</option>
                                            <option value="Punjab">Punjab</option>
                                            <option value="Rajasthan">Rajasthan</option>
                                            <option value="Sikkim">Sikkim</option>
                                            <option value="Tamil Nadu">Tamil Nadu</option>
                                            <option value="Telangana">Telangana</option>
                                            <option value="Tripura">Tripura</option>
                                            <option value="Uttar Pradesh">Uttar Pradesh</option>
                                            <option value="Uttarakhand">Uttarakhand</option>
                                            <option value="West Bengal">West Bengal</option>
                                        </select>
                                </div>
                                <div class="checkout__form__input">
                                    <p>Postcode/Zip <span style="color :red">*</span></p>
                                    <input type="text" name="pin_code" required>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="checkout__form__input">
                                    <p>Phone <span style="color :red">*</span></p>
                                    <input type="tel" name="phone" required>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="checkout__form__input">
                                    <p>Email <span></span></p>
                                    <input type="email" name="email">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
        <!-- Checkout Section End -->
{% endblock %}

templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block body %}

    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="index.html"><i class="fa fa-home"></i> Home</a>
                        <span>Contact</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Contact Section Begin -->
    <section class="contact spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="contact__content">
                        <div class="contact__form">
                            <h5>SEND MESSAGE</h5>
                            <form  class="checkout__form ajax reload redirect"  method="POST"> 
                                {% csrf_token %}    
                                <input type="text" placeholder="Name"  name="name" required>
                                <input type="email" placeholder="Email"  name="email" required>
                                <input type="text" placeholder="Phone"  name="phone" required>
                                <textarea placeholder="Message" name="message" required ></textarea>
                                <input type="submit" class="site-btn" style="color:#fff" name="Send Message"></input>
                            </form> 
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Contact Section End -->
{% endblock %}

templates/privacy_policy.html
{% extends "base.html" %}
{% load static %}
{% block body %}

    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="/"><i class="fa fa-home"></i> Home</a>
                        <span>Shipping Policy</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Shop Section Begin -->
    <section class="shop spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <h1>PRIVACY POLICY</h1>
                    <h2 style="font-size:18px;text-align:left;margin-bottom:0px">Collecting Personal Information</h2>
                    When you visit the Site, we collect certain information about your device, your interaction with the Site, and information necessary to process your purchases. We may also collect additional information if you contact us for customer support. In this Privacy Policy, we refer to any information that can uniquely identify an individual (including the information below) as “Personal Information”. See the list below for more information about what Personal Information we collect and why.
                    <br>
                    <br>
                    <h2 style="font-size:18px;text-align:left;margin-bottom:0px">Device information</h2>      
                        • Examples of Personal Information collected: version of web browser, IP address, time zone, cookie information, what sites or products you view, search terms, and how you interact with the Site.<br>
                        • Purpose of collection: to load the Site accurately for you, and to perform analytics on Site usage to optimize our Site.<br>
                        • Source of collection: Collected automatically when you access our Site using cookies, log files, web beacons, tags, or pixels [ADD OR SUBTRACT ANY OTHER TRACKING TECHNOLOGIES USED].<br>
                        • Disclosure for a business purpose: shared with our processor Shopify [ADD ANY OTHER VENDORS WITH WHOM YOU SHARE THIS INFORMATION].<br>
                  <br>
                  <br>
                    <h2 style="font-size:18px;text-align:left;margin-bottom:0px"> Order information</h2>     
                    •	Examples of Personal Information collected: name, billing address, shipping address, payment information (including credit card numbers [INSERT ANY OTHER PAYMENT TYPES ACCEPTED]), email address, and phone number.<br>
                    •	Purpose of collection: to provide products or services to you to fulfill our contract, to process your payment information, arrange for shipping, and provide you with invoices and/or order confirmations, communicate with you, screen our orders for potential risk or fraud, and when in line with the preferences you have shared with us, provide you with information or advertising relating to our products or services.<br>
                    •	Source of collection: collected from you.<br>
                    •	Disclosure for a business purpose: shared with our processor Shopify [ADD ANY OTHER VENDORS WITH WHOM YOU SHARE THIS INFORMATION. FOR EXAMPLE, SALES CHANNELS, PAYMENT GATEWAYS, SHIPPING AND FULFILLMENT APPS].<br>
                  <br>
                  <br>
                    <h2 style="font-size:18px;text-align:left;margin-bottom:0px">   Customer support information</h2>
                    •	Examples of Personal Information collected: [MODIFICATIONS TO THE INFORMATION LISTED ABOVE OR ADDITIONAL INFORMATION AS NEEDED]<br>
                    •	Purpose of collection: to provide customer support.<br>
                    •	Source of collection: collected from you.<br>
                    •	Disclosure for a business purpose: [ADD ANY VENDORS USED TO PROVIDE CUSTOMER SUPPORT]<br>
                  
                    
                    

                </div>
            </div>
        </div>
    </section>
    <!-- Shop Section End -->

{% endblock %}

templates/refund_policy.html
{% extends "base.html" %}
{% load static %}
{% block body %}

    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__links">
                        <a href="/"><i class="fa fa-home"></i> Home</a>
                        <span>Refund Policy</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Shop Section Begin -->
    <section class="shop spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <h1>REFUND POLICY</h1>
                        All orders can be cancelled until they are shipped. If your order has been paid and you need to change or cancel it, you must contact us within 12 hours. Once the packaging and shipping process has started, it can no longer be cancelled.
                        Refunds/Replacement (7 Day Refund/Replacement)
                        We offer a 100% money back guarantee/Replacement Guarantee on all products that are damaged during shipping. Just let us know On This Email Address (EFUDEXSTORE@GMAIL.COM) With Video Proof And Shipment Label Also Within 7 Hours Of Delivery and we will provide a return address.
                        note - an unboxing video is needed when asking replacement or refund
                        Customers will be responsible for paying return shipping costs.
                        <br>
                        We do not issue the refund if:
                        <br>
                        ● your order does not arrive due to factors within your control (e.g. providing the wrong shipping address)

                </div>
            </div>
        </div>
    </section>
    <!-- Shop Section End -->

{% endblock %}